Algoritmo "areatriangulo"

// Descrição   : Solicita a base e altura e calcula a area do Triangulo
// Autor(a)    : Stephanie Mota
// Data atual  : 08/03/2022
Var
base, alt, area:real


Inicio
//entrada
escreval("Digite a base do Triangulo:")
leia(base)
escreval("Digite a altura do Triangulo:")
leia(alt)

//processamento
area <- (base*alt)/2

//saida
escreval ("A area do Triangulo é:", area)


Fimalgoritmo